### ISSUE TITLE
Move to JuliaImages?

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageInTerminal.jl#1]
Hi @timholy !

I am working on this package currently. Because I am pretty much exclusively working over SSH in vim, it is quite bothersome to fire up notebooks just to display images.

Essentially I use Unicode characters and ANSI-colors (the 256 colors almost all terminal support) to "render" the image as text.

- large images: I use a character as two pixel by setting different foreground and background colors and printing `▀` (upper half block). I downscale images to fit the `displaysize` using restrict.

- small images: I use two characters as a single pixel by printing two `█` (full block).

<img width="521" alt="screen shot 2017-02-12 at 12 27 53" src="https://cloud.githubusercontent.com/assets/10854026/22861672/0330f650-f11f-11e6-975d-f0d3cd85c545.png">

Do you think this could be useful to your ecosystem? If overwriting `show` is too much we could also just expose a `imshow` function, but I think it is actually quite convenient.

Let me know your thoughts.

**Comment by Evizero** [comment]
bigger example:

<img width="534" alt="screen shot 2017-02-12 at 12 36 30" src="https://cloud.githubusercontent.com/assets/10854026/22861696/00dfa51c-f120-11e6-97d7-6985215b3805.png">

**Comment by timholy** [comment]
That's really cool :1st_place_medal: . Definitely useful, and it would be fine to move it to JuliaImages if you like.

**Comment by Evizero** [comment]
Glad you like it. Yes, I mainly ask because then I will not bother setting up CI before the move (since switching repo is bothersome). Further I'll try to match the look of the readme.

I tell you what, I'll get this package to a state where I think it is feature complete and properly tested and then I'll ping you about performing the move.

Sounds like a plan?

**Comment by Evizero** [comment]
(I'll of course continue to maintain it there.)

**Comment by Evizero** [comment]
On a related note. How do you think about moving `restrict` from `Images` to `ImageCore`? It is basically the only reason why I need to depend on Images.

**Comment by timholy** [comment]
I'd prefer to keep `ImageCore` to be about truly low-level stuff, basically conversions/views/traits/etc. `restrict` is a "real" algorithm, which places it at a different level.

How about we try to turn `ImageTransformations` into a real package? `imresize` should go there too.

**Comment by Evizero** [comment]
good idea!

**Comment by Evizero** [comment]
If you want I'll attempt the port from Images.jl to ImageTransformations.jl later today. `restrict` and `imresize`, right?

**Comment by timholy** [comment]
Sounds great!

**Comment by Evizero** [comment]
I am considering how to render colorant vectors

<img width="640" alt="screen shot 2017-02-12 at 18 17 44" src="https://cloud.githubusercontent.com/assets/10854026/22864334/c32c2e5e-f14f-11e6-911e-38027c6eeeb0.png">

Would you say it would be more informative to `restrict` them as well if too big, or should we do the "..." thing that arrays do (as shown in the image above).

**Comment by timholy** [comment]
Interesting question. Since you don't use `...` for matrices, perhaps more consistent to `restrict`? I could be persuaded otherwise.

**Comment by Evizero** [comment]
The problem with `restrict` for vectors is that it makes it look weird that big vectors don't fill up all the horizontal space. Hmm, I'll try `imresize` for vectors. see how that looks

**Comment by Evizero** [comment]
I now added support for visualizing an alpha channel and also enrich how single colorants are rendered. Now "all" I have to do is write meaningful tests and we are good to go

<img width="354" alt="screen shot 2017-02-13 at 16 01 01" src="https://cloud.githubusercontent.com/assets/10854026/22888502/420bfe8c-f206-11e6-8d83-3bbc59b65060.png">

**Comment by Evizero** [comment]
Hey @timholy ! The tests are now in place and I think this package is ready to move. I don't think I have the permissions to move anything to JuliaImages. How should we proceed? I could invite you to this package

**Comment by timholy** [comment]
Awesome.

Now you should have the requisite permissions. Welcome, young Jedi. :smile:

**Comment by Evizero** [comment]
Thanks!

> You don’t have the permission to create repositories on JuliaImages 

Did not work yet

**Comment by Evizero** [comment]
Maybe moving requires too many permissions? In order to not fish for more permissions than I really require I added you as collaborator to this package. Maybe this is an easier way to perform the move

**Comment by timholy** [comment]
I can't do it without being an "owner" of this repo. But I think I messed it up; can you try again?

**Comment by Evizero** [comment]
success! Thank you. I'll see if I can set up CI and such

**Comment by Evizero** [comment]
I enabled Travis and Appyevor. Would you mind enabling codecov? I only have a coveralls account and since all other JuliaImage libraries use codecov I don't want to break the tradition

**Comment by Evizero** [comment]
Very nice. Thanks. 

I'll wait for all the 0.5 tests to pass on CI and then go ahead an register the package!

I'll introduce Compat for 0.6 support in a later release. I did not look into that aspect yet. (same applies to ImageTransformations)
