### ISSUE TITLE
`imshow` in endless loop for non collorant matrix

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageInTerminal.jl#10]
Discovered this on accident

```julia
using ImageInTerminal

imshow(sprand(10,10,0.2)) # hangs forever

imshow(rand(10,10)) # also hangs forever
```

Have not looked into it yet. ~~Probably the `while` loop that downscaled the array~~ EDIT: no.

These are pretty serious bugs. Regardless of if non-colorant arrays are supported, it must not be caught in an endless loop

**Comment by Evizero** [comment]
Oh I see the problem I think. Has nothing to do with the `while` loop, because those methods require `Colorant` arrays. It actually must get stuck calling itself here

https://github.com/JuliaImages/ImageInTerminal.jl/blob/master/src/imshow.jl#L49-L50

because it doesn't find a more specialized method

**Comment by timholy** [comment]
Yes, that's right. To be robust, you'll need a fallback for where the `colormode` has been supplied but which does not otherwise specify the type of `img`. (In other words, simply loosening the eltype restriction to `C<:Union{Number,Colorant}` would still be living dangerously.)

**Comment by Evizero** [comment]
My thoughts exactly. see #11
