### ISSUE TITLE
[RFC] Don't export imshow/imshow256/imshow24bit

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageInTerminal.jl#32]
Compared with the standard `show` method, I find myself rarely use these functions, perhaps it's a good idea to not export them.

I don't have plans on doing it recently, just open this issue to see how others feel about it. (For example, with :+1: or :-1:)

**Comment by t-bltg** [comment]
Closed by https://github.com/JuliaImages/ImageInTerminal.jl/pull/58.
