### ISSUE TITLE
Register in METADATA

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageInTerminal.jl#4]
The package currently works on Linux and OSX for Julia 0.5. I think that is worth a register.

- For now it does not work properly on windows. The string processing seems to be different. Need to look into that. Regardless of that problem as far as I know windows doesn't have 256 color support yet anyway, so I'll fix this later.

- It also does not yet work on 0.6. That should be an easier fix using Compat, which I will probably do in the next release.

**Comment by Evizero** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8223

**Comment by tkelman** [comment]
https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

**Comment by Evizero** [comment]
Thanks! will look into that
