### ISSUE TITLE
better image encoding via sixel

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageInTerminal.jl#45]
[sixel](https://github.com/saitoha/libsixel) has way better image display quality in the terminal so we should consider adopting this.

It is a C library so we need to first build the `libsixel_jll` with [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl), and then wrap it with perhaps `Sixel.jl`, and use the wrapping package in ImageInTerminal.

https://github.com/m-j-w/TerminalGraphics.jl is a very early project to do this before the "modern" BinaryBuilder.

**Comment by johnnychen94** [comment]
it's still WIP, but here's a preview:

![image](https://user-images.githubusercontent.com/8684355/116808445-5a506280-ab6b-11eb-98ec-ba95359005e7.png)

**Comment by johnnychen94** [comment]
@oxinabox FYI, with this done (https://github.com/johnnychen94/Sixel.jl/pull/1), ReferenceTests will then include `libsixel_jll` for Julia >= v1.6 in exchange for the much better terminal image comparison.

**Comment by oxinabox** [comment]
Nice
TIL
https://en.wikipedia.org/wiki/Sixel
