### ISSUE TITLE
`TagBot` fails

### ISSUE THREAD

**Issue by t-bltg** [JuliaImages/ImageInTerminal.jl#70]
https://github.com/JuliaImages/ImageInTerminal.jl/runs/7752079783?check_suite_focus=true#step:3:49:

```
/usr/bin/docker run --name ghcriojuliaregistriestagbot1141_3b4b7e --label 4cd98f --workdir /github/workspace --rm -e INPUT_TOKEN -e INPUT_SSH -e INPUT_REGISTRY -e INPUT_GITHUB -e INPUT_GITHUB_API -e INPUT_BRANCHES -e INPUT_DISPATCH -e INPUT_DISPATCH_DELAY -e INPUT_LOOKBACK -e INPUT_SSH_PASSWORD -e INPUT_GPG -e INPUT_GPG_PASSWORD -e INPUT_REGISTRY_SSH -e INPUT_DRAFT -e INPUT_USER -e INPUT_EMAIL -e INPUT_BRANCH -e INPUT_CHANGELOG -e INPUT_CHANGELOG_IGNORE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ImageInTerminal.jl/ImageInTerminal.jl":"/github/workspace" ghcr.io/juliaregistries/tagbot:1.14.1
Processing version v0.5.0 (b1d0b585bb6c116aa41e9511f5aa326fcf5bb4db)
Generating changelog for version v0.5.0 (b1d0b585bb6c116aa41e9511f5aa326fcf5bb4db)
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 533, in create_release
    self._git.create_tag(version, sha, log)
  File "/root/tagbot/action/git.py", line 107, in create_tag
    self.command("push", "origin", version)
  File "/root/tagbot/action/git.py", line 71, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_9ci4a1by push origin v0.5.0' failed

Response (200): {
  "status": "Submitted error report"
}
```

Also fails on `XTermColors`: https://github.com/JuliaImages/XTermColors.jl/runs/7751221920?check_suite_focus=true#step:3:49

Seems related to the `JuliaImages` organization secrets: `DOCUMENTER_KEY` and `TAGBOT`.

@johnnychen94, do you know how to fix this ?

**Comment by johnnychen94** [comment]
Added.

**Comment by t-bltg** [comment]
Odd, when you retry it works. I'm cursed :laughing: Thanks.

**Comment by johnnychen94** [comment]
Oh, this was an admin operation from my side -- I generated them manually to fix the action.

> Seems related to the JuliaImages organization secrets: DOCUMENTER_KEY and TAGBOT.

I had once added an organization level secrets `DOCUMENTER_KEY` and `TAGBOT` but it turns out that they never work.

To properly set up the ssh key, we'd need to add it to both deploy keys (`id_rsa.pub` content) and secret (`id_rsa` content) in repository settings. It has to be paired to authorize Tagbot with the write permission.
It seems that I can't set an organization-level deploy key, so the organization-level secrets `DOCUMENTER_KEY` and `TAGBOT` won't work at all.

**Comment by t-bltg** [comment]
In 2 repositories that I have created (so that I can access and list `<repo>/settings/secrets/actions`):

**MarchingCubes.jl**
![mc_secrets png](https://user-images.githubusercontent.com/13423344/183845394-758c291a-08d4-482a-b0c7-c137ef7b6920.png)


(tagbot works)

**XTermColors.jl**
![xterm_colors](https://user-images.githubusercontent.com/13423344/183844945-a8030227-dc34-4de2-b680-9f48831f3306.png)

(tagbot was failing, but I think that you just added recent `Repository Secrets`, right ?)

> I had once added an organization level secrets DOCUMENTER_KEY and TAGBOT but it turns out that they never work.

So I think that deleting all secrets from `JuliaImages` should just work no ?

**Comment by johnnychen94** [comment]
> So I think that deleting all secrets from JuliaImages should just work no ?

Maybe, I'm not sure.
